// src/pages/access/ResetPassword.jsx
import React, { useState, Component } from 'react';
import { Form, Button, Row, Col } from 'react-bootstrap';
import { Link } from 'react-router-dom';
import LogoSVG  from './../../assets/svg/bBOV3E01.svg';
import { sendEmail, loginCheck } from '../../services/UserService';

class ResetPassword extends Component {
  constructor(props) {
    document.title = 'Cambiar Contraseña';
    super(props);
    this.state = {
      email: '',
      message: '',
      messageClass: '',
      disabled: false,
      isValidJWT: false,
      isValidEmail: true,
    };
    this.emailInputRef = React.createRef();
  }

  componentDidMount() {
    const token = localStorage.getItem('jwtToken');
    if (token != null) {
      loginCheck()
        .then(data => {
          if (data.success == true){
            // token time expired, continue to login
            this.setState({
              isValidJWT: true,
            });
          }
        })
        .catch(error => {
          console.error("Error:", error);
        });      
    }
  }

  validateForm() {
    const { email } = this.state;
    if(email !== ''){
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (emailRegex.test(email)) {
        return true;
      } else {
        this.setState({ 
          message: 'Debe ingresar un correo válido', 
          messageClass: 'text-danger' 
        });
      }
    }else{
      this.setState({ 
        message: 'Debe de llenar el formulario', 
        messageClass: 'text-danger' 
      });
    }
    setTimeout(() => {
      this.setState({ 
        message: '', 
        messageClass: '' 
      });
    }, 5000);
    setTimeout(() => {
      this.setState({ 
        disabled: false, 
      });
    }, 1500);
    return false;
  }

  submit = (event) => {
    event.preventDefault();
    const { email } = this.state;
    const { history } = this.props;
    if (this.validateForm()) {
      this.setState({ disabled: true });
      sendEmail(email)
        .then(data => {
          let continueToApp = false;
          let timeout = 4500;
          if (!data.success) {
            this.setState({
              messageClass: 'text-danger',
              message: data.message,
              disabled: false
            });
          } else {
            continueToApp = true;
            timeout = 1500;
            this.setState({
              messageClass: 'text-success',
              message: 'Se le ha enviado un correo para que pueda cambiar su constraseña'
            });
          }
          if (!continueToApp) {
            this.emailInputRef.current.focus();
            this.emailInputRef.current.select();
          }else{
            this.setState({ 
              disabled: true, 
            });
            setTimeout(() => {
              this.setState({ 
                message: '', 
                messageClass: '' ,
                disabled: false,
              });
            }, 5000);
          }
        })
        .catch(error => {
          console.error(error);
          this.setState({ 
            message: 'Ocurrió un error al enviar el correo de cambio de contreña',
            messageClass: 'text-danger' 
          });
          setTimeout(() => {
            this.setState({ 
              message: '', 
              messageClass: '' 
            });
          }, 5000);
          setTimeout(() => {
            this.setState({ 
              disabled: false, 
            });
          }, 1500);
        });
    }
  };

  render() {
    const {message, messageClass, disabled, isValidJWT} = this.state;
    if (isValidJWT) {
      window.location.href = '/';
      return null;
    }
    return (
      <>
      <div className="form-container">
        <div className="logo-container">
          <img src={LogoSVG} className="logo custom-color" alt="Vite logo" />
        </div>
        <Form onSubmit={this.submit} style={{width: '300px'}} className="row mt-2" >
          <Form.Group controlId="formBasicEmail">
            <Form.Label>Correo</Form.Label>
            <Form.Control
              type="text"
              placeholder="Ingrese su correo"
              value={this.email}
              onChange={(e) => this.setState({ email: e.target.value })}
              ref={this.emailInputRef}
              className="is-invalid"
            />
          </Form.Group>
          <Form.Text className="text-danger">Por favor, ingrese un correo electrónico válido.</Form.Text>
          <Form.Label className={`${messageClass} mt-2 text-center`}>{message}</Form.Label>
          <Button variant="primary" type="submit" className="w-100 mt-2">
            Enviar Solicitud
          </Button>
        </Form>
        <Row className="mt-2">
          <Col>
            <div className="left-aligned-content">
              <Link to="/login" className="link" style={{ textAlign: 'left' }}>Ingresar</Link>
            </div>
          </Col>
          <Col>
            <div className="right-aligned-content" style={{'textAlign': 'right'}}>
              <Link to="/sign-in" className="link" style={{ textAlign: 'right' }}>Crear cuenta</Link>
            </div>
          </Col>
        </Row>
      </div>
      <Row className="mt-2">
        <footer className="mt-3" style={{textAlign: 'left', paddingLeft: '14px'}}>
          Powered by Software Web Perú 2023. <a style={{fontWeight: 400}} className="link" target="_blank" href="https://softweb.pe">Ir</a>.
        </footer>
      </Row>
    </>
    );
  }
}

export default ResetPassword;

// src/components/pages/access/ResetPassword.svelte
<script>
  import { onMount } from 'svelte';
  import { navigate } from 'svelte-routing';
  import Logo from '../../svgs/Logo.svelte';
  import InputEmail from '../../widgets/InputEmail.svelte';
  import { resetPassword } from '../../../services/user_service.js';
  
  let message = '';
  let messageClass = '';
  let email = ''; let emailInput;

  onMount(() => {

  });

  const reset = (event) => {
    event.preventDefault();
    // run validations
    emailInput.validate();
    // if ok, ajax
    if(emailInput.isValid){
      let data = {
        email: email, 
      };
      resetPassword(data).then((resp) => {
          //console.log(resp)
          message = resp.data;
          messageClass = 'text-success';
          setTimeout(() => {
            message = '';
            messageClass = '';
          }, 4000);
        }).catch((resp) =>  {
          //console.log(resp)
          message = resp.data;
          messageClass = 'text-danger';
          setTimeout(() => {
            message = '';
            messageClass = '';
          }, 4000);
        })
    }
  }
</script>
<style></style>

<svelte:head>
	<title>Recuperar Contraseña</title>
</svelte:head>

<div class="container mt-5">
  <div class="row justify-content-center mb-4">
    <Logo size=48 color='#0000002d'/>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          <h3 class="text-center">Olvidó su Contraseña</h3>
        </div>
        <div class="card-body">
          <form>
            <div class="mb-3">
              <InputEmail 
                id="email" 
                label="Correo Electrónico" 
                bind:value={email} 
                bind:this={emailInput}
                onInputValidation={true}
                validations = {[
                  {type: 'notEmpty', message: 'Ingresar un correo'},
                  {type: 'validEmail', message: 'Correo no válido'},
                ]} />
            </div>
            <button type="submit" on:click={reset} class="btn btn-primary w-100">Enviar Correo</button>
          </form>
          <div class="text-center mt-3 {messageClass}">
            {message}
          </div>
          <div class="text-center mt-3">
            <a class="navbar-brand" href="/login" on:click|preventDefault={() => {navigate('/login')}}>Ingresar</a>
            <span class="mx-2">|</span>
            <a class="navbar-brand" href="/sign-up" on:click|preventDefault={() => {navigate('/sign-up')}}>Crear Cuenta</a>
          </div>
        </div>
        <div class="card-footer text-center">
          <small>&copy; 2024 Your Brand</small>
        </div>
      </div>
    </div>
  </div>
</div>
